# Generated by Django 4.0.4 on 2022-06-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videos',
        ),
    ]
