# Generated by Django 4.0.4 on 2022-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('created_in', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
