# Generated by Django 4.0.4 on 2022-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggle', '0004_alter_activelock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelock',
            name='method',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
